name: my_devices
description: "Manage all your devices in one place. Add details, upload pictures, update status."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.23.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^21.0.0-dev.2
  http: ^1.0.0
  flutter_offline: ^6.0.0
  image_cropper: ^11.0.0
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  easy_localization: ^3.0.5
  flutter_native_splash: ^2.2.19
  liquid_swipe: ^3.0.0
  dio: ^5.9.1
  uuid: ^4.5.3
  timezone: ^0.11.0
  connectivity_plus: ^7.0.0
  intl: ^0.20.2



flutter_native_splash:
  android: true
  color: "#36013F"
  image: assets/images/icon.png
  android_gravity: fill_horizontal
  android_12:
    android_gravity: fill_horizontal
    color: "#36013F"
    image: assets/images/icon.png

    # dart run flutter_native_splash:remove
    # dart run flutter_native_splash:create
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/fallbackImage.jpg
     - assets/images/defaultProfilePicture.jpg
     - assets/images/icon.png
     - assets/translations/
  fonts:
    - family: Ge_ss
      fonts:
        - asset: assets/fonts/GE_SS.otf
